apiVersion: v1
kind: Service
metadata:
  name: python-flask-ml-score-api
  namespace: ml-serving
  labels:
    app: ml-score-api
spec:
  selector:
    app: ml-score-api
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 5000
  type: LoadBalancer
